title: Your Site's Title
email: your-email@example.com
description: > # this means to ignore newlines until "baseurl:"
  This is a short description of what your site is about.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

theme: minima # or any other theme you choose
